config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/graphql', to: 'graphql#execute'
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  ActiveAdmin.routes(self)
  mount Lookbook::Engine, at: '/lookbook'

  resources :tire_sets, param: :uuid
  resources :vehicles, param: :uuid do
    resources :odometer_readings, param: :uuid
    resources :log_items, param: :uuid
  end

  root 'vehicles#index'

  get '/login' => 'auth0#login'
  get '/auth/auth0/callback' => 'auth0#callback'
  post '/auth/developer/callback' => 'auth0#developer_callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'auth0#logout'

  get '/user' => 'user#me'
  put '/user' => 'user#update_me'
end

app/models/odometer_reading.rb
# frozen_string_literal: true

class OdometerReading < ApplicationRecord
  belongs_to :vehicle
  has_one :log_item, dependent: :nullify
  validates :reading, presence: true
  validates :performed_at, presence: true

  owner_from_parent :vehicle, Vehicle

  def attach_to_log_item(log_item)
    self.log_item = log_item
    self.performed_at = log_item.performed_at
  end

  scope :chrono, -> { order(performed_at: :asc) }
  scope :inverse_chrono, -> { order(performed_at: :desc) }
  scope :order_by_closest_to, lambda { |date|
    order(ArelHelpers.abs(ArelHelpers.date_part('epoch', performed_at - ArelHelpers.to_timestamp(date))).asc)
  }
  scope :closest_to, ->(date) { order_by_closest_to(date).first }
  scope :first_before, ->(date) { where(OdometerReading.arel_table[:performed_at].lt(date)).inverse_chrono.first }
  scope :soonest_after, ->(date) { where(OdometerReading.arel_table[:performed_at].gt(date)).chrono.first }

  def gid_class_name
    'odometer_reading'
  end
end

app/controllers/odometer_readings_controller.rb
# frozen_string_literal: true

class OdometerReadingsController < ApplicationController
  SET_ACTIONS = %i[edit update destroy].freeze

  include Secured
  include Pundit::Authorization
  after_action :verify_authorized
  after_action :verify_policy_scoped, only: SET_ACTIONS + %i[index]

  before_action :set_vehicle
  before_action :set_odometer_reading, only: SET_ACTIONS

  # GET /vehicles/1/odometer_readings or /vehicles/1/odometer_readings.json
  def index
    @odometer_reading = OdometerReading.new(vehicle: @vehicle, performed_at: current_user.now) if policy(@vehicle).edit?
    @odometer_readings = policy_scope(OdometerReading).merge(@vehicle.odometer_readings).includes(:log_item)
  end

  # GET /vehicles/1/odometer_readings/1/edit
  def edit; end

  # POST /vehicles/1/odometer_readings or /vehicles/1/odometer_readings.json
  def create
    @odometer_reading = OdometerReading.new(odometer_reading_params)
    @odometer_reading.vehicle = @vehicle
    authorize @odometer_reading

    respond_to do |format|
      if @odometer_reading.save
        format.html do
          redirect_to vehicle_odometer_readings_url(@odometer_reading.vehicle),
                      notice: I18n.t('odometer_reading.create.success')
        end
        format.json { render :show, status: :created, location: @odometer_reading }
      else
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @odometer_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1/odometer_readings/1 or /vehicles/1/odometer_readings/1.json
  def update
    respond_to do |format|
      if @odometer_reading.update(odometer_reading_params)
        format.html do
          redirect_to edit_vehicle_odometer_reading_url(@vehicle, @odometer_reading),
                      notice: I18n.t('odometer_reading.update.success')
        end
        format.json { render :show, status: :ok, location: @odometer_reading }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @odometer_reading.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1/odometer_readings/1 or /vehicles/1/odometer_readings/1.json
  def destroy
    @odometer_reading.destroy

    respond_to do |format|
      format.html do
        redirect_to vehicle_odometer_readings_url(@vehicle), notice: I18n.t('odometer_reading.destroy.success')
      end
      format.json { head :no_content }
    end
  end

  def current_navbar_item
    :vehicles
  end

  private

  def set_vehicle
    @vehicle = policy_scope(Vehicle).find_by(uuid: params[:vehicle_uuid])
    authorize @vehicle
  end

  def set_odometer_reading
    @odometer_reading = policy_scope(OdometerReading).merge(@vehicle.odometer_readings).find_by(uuid: params[:uuid])
    authorize @odometer_reading
  end

  # Only allow a list of trusted parameters through.
  def odometer_reading_params
    extracted_params = params.require(:odometer_reading).permit(:reading, :include_time, :performed_at)
    transform_performed_at(extracted_params)
    extracted_params
  end
end

app/views/odometer_readings/_form.html.erb
<%= bootstrap_form_with(model: [vehicle, odometer_reading]) do |form| %>
  <p>
    <%= OdometerReading.human_attribute_name(:vehicle) %>:
    <%= link_to @vehicle.display_name, vehicle_path(@vehicle) %>
  </p>
  <%= form.text_field :reading %>
  <%= form.datetime_field :performed_at,
                          value: convert_for_datetime_field(odometer_reading.performed_at),
                          max: convert_for_datetime_field(Time.now) %>
  <p><%= t 'current_time_zone' %>: <%= current_user.tz.name %></p>
  <%= form.check_box :include_time %>
  <%= form.submit %>
<% end %>

app/views/odometer_readings/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item"><%= link_to @vehicle.display_name, vehicle_path(@vehicle) %></li>
    <li class="breadcrumb-item"><%= link_to t('odometer_reading.list.title'), vehicle_odometer_readings_url(@vehicle) %></li>
    <li class="breadcrumb-item"><%=
      I18n.t(
        'odometer_reading.preview',
        reading: number_with_delimiter(@odometer_reading.reading),
        performed_at: display_time(
          @odometer_reading.performed_at,
          format: if @odometer_reading.include_time
                    :date_and_time
                  else
                    :date_only
                  end
        )
      )
    %></li>
    <li class="breadcrumb-item active"><%= t 'odometer_reading.editing' %></li>
  </ol>
</nav>

<h1><%= t 'odometer_reading.editing' %></h1>

<%= render 'form', vehicle: @vehicle, odometer_reading: @odometer_reading %>

<br>

<div>
  <%= link_to t('odometer_reading.link.back'), vehicle_path(@odometer_reading.vehicle) %>
</div>

app/views/odometer_readings/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item"><%= link_to @vehicle.display_name, vehicle_path(@vehicle) %></li>
    <li class="breadcrumb-item active"><%= t 'odometer_reading.list.title' %></li>
  </ol>
</nav>

<h1>
  <%= t 'vehicle.odometer_title',
        vehicle: @vehicle.display_name,
        miles: t('miles', miles: number_with_delimiter(@vehicle.odometer)) %>
</h1>

<p>
  <%= link_to t('vehicle.link.vehicle_back', vehicle: @vehicle.display_name), vehicle_path(@vehicle) %>
</p>

<% default_accordion_item = if @odometer_reading && @vehicle.odometer_readings.empty?
                              :record
                            else
                              :list
                            end %>

<%= render AccordionComponent.new do |c| %>
  <% if @odometer_reading %>
    <% c.with_item(expanded: default_accordion_item == :record, title: t('odometer_reading.create.title')) do %>
      <%= render 'form', vehicle: @vehicle, odometer_reading: @odometer_reading %>
    <% end %>
  <% end %>
  <% c.with_item(expanded: default_accordion_item == :list, title: OdometerReading.model_name.human(count: @vehicle.odometer_readings.count)) do %>
    <ul>
      <% @odometer_readings.inverse_chrono.each do |odometer_reading| %>
        <li class="my-1">
          <div class="d-flex align-items-center">
            <%=
              I18n.t(
                'odometer_reading.preview',
                reading: number_with_delimiter(odometer_reading.reading),
                performed_at: display_time(
                  odometer_reading.performed_at,
                  format: if odometer_reading.include_time
                            :date_and_time
                          else
                            :date_only
                          end
                )
              )
            %>
            <% if odometer_reading.log_item %>
              <%= link_to t('odometer_reading.link.log_item'), vehicle_log_item_path(@vehicle, odometer_reading.log_item), class: 'mx-1 btn btn-sm btn-primary' %>
            <% end %>
            <%= link_to t('odometer_reading.link.edit'), edit_vehicle_odometer_reading_path(@vehicle, odometer_reading), class: 'mx-1 btn btn-sm btn-secondary' %>
            <%= button_to t('odometer_reading.link.destroy'), vehicle_odometer_reading_path(@vehicle, odometer_reading), method: :delete, class: 'mx-1 btn btn-sm btn-danger' %>
          </div>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>