config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/graphql', to: 'graphql#execute'
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  ActiveAdmin.routes(self)
  mount Lookbook::Engine, at: '/lookbook'

  resources :tire_sets, param: :uuid
  resources :vehicles, param: :uuid do
    resources :odometer_readings, param: :uuid
    resources :log_items, param: :uuid
  end

  root 'vehicles#index'

  get '/login' => 'auth0#login'
  get '/auth/auth0/callback' => 'auth0#callback'
  post '/auth/developer/callback' => 'auth0#developer_callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'auth0#logout'

  get '/user' => 'user#me'
  put '/user' => 'user#update_me'
end

app/models/log_item.rb
# frozen_string_literal: true

class LogItem < ApplicationRecord
  belongs_to :vehicle
  belongs_to :shop, optional: true
  belongs_to :odometer_reading, optional: true, autosave: true
  has_many :line_items, dependent: :destroy

  before_save :copy_odometer_reading_time
  before_create :copy_odometer_reading_time

  owner_from_parent :vehicle, Vehicle

  scope :chrono, -> { order(performed_at: :asc) }
  scope :inverse_chrono, -> { order(performed_at: :desc) }
  scope :with_line_item_type, ->(type) { joins(:line_items).where(line_item: { type_id: type }).distinct(:id) }

  def copy_odometer_reading_time
    return unless odometer_reading

    odometer_reading.performed_at = performed_at
    odometer_reading.include_time = include_time
  end

  def added_tire_sets
    TireSet.joins(line_item_fields: :line_item).merge(LineItem.where(type_id: 'mountedTires', log_item: self))
  end

  def removed_tire_sets
    TireSet.joins(line_item_fields: :line_item).merge(LineItem.where(type_id: 'dismountedTires', log_item: self))
  end

  def odometer_reading_reading
    odometer_reading&.reading
  end

  def odometer_reading_reading=(reading)
    if odometer_reading
      if reading.present?
        odometer_reading.reading = reading
        odometer_reading.include_time = include_time
      else
        odometer_reading.destroy!
      end
    elsif reading.present?
      self.odometer_reading = OdometerReading.new(vehicle:, reading:, performed_at:, include_time:)
    end
  end

  def shop_uuid
    shop&.uuid
  end

  def shop_uuid=(new_uuid)
    self.shop = Shop.find_by(uuid: new_uuid)
  end

  def gid_class_name
    'log_item'
  end
end

app/controllers/log_items_controller.rb
# frozen_string_literal: true

class LogItemsController < ApplicationController
  SET_ACTIONS = %i[show edit update destroy].freeze

  include Secured
  include Pundit::Authorization
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: SET_ACTIONS + %i[index]

  before_action :set_vehicle
  before_action :set_log_item, only: SET_ACTIONS
  before_action :set_shops, only: %i[new create edit update]

  # GET /vehicles/1/log_items or /log_items.json
  def index
    @log_items = @vehicle.log_items.merge(policy_scope(LogItem))
  end

  # GET /vehicles/1/log_items/1 or /log_items/1.json
  def show
    set_log_item_with_includes({ line_items: :line_item_fields })
  end

  # GET /vehicles/1/log_items/new
  def new
    @log_item = LogItem.new(vehicle: @vehicle, performed_at: current_user.now)
    authorize @log_item
  end

  # GET /vehicles/1/log_items/1/edit
  def edit; end

  # POST /vehicles/1/log_items or /vehicles/1/log_items.json
  def create
    @log_item = LogItem.new(log_item_params.except(:odometer_reading_reading))
    @log_item.vehicle = @vehicle
    @log_item.odometer_reading_reading = log_item_params[:odometer_reading_reading]
    authorize @log_item

    respond_to do |format|
      if @log_item.save
        format.html { redirect_to vehicle_log_item_url(@vehicle, @log_item), notice: I18n.t('log_item.create.success') }
        format.json { render :show, status: :created, location: @log_item }
      else
        Rails.logger.debug @log_item.errors.to_json
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @log_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1/log_items/1 or /vehicles/1/log_items/1.json
  def update
    respond_to do |format|
      if @log_item.update(log_item_params)
        format.html { redirect_to vehicle_log_item_url(@vehicle, @log_item), notice: I18n.t('log_item.update.success') }
        format.json { render :show, status: :ok, location: @log_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @log_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1/log_items/1 or /vehicles/1/log_items/1.json
  def destroy
    @log_item.destroy

    respond_to do |format|
      format.html { redirect_to vehicle_log_items_url(@vehicle), notice: I18n.t('log_item.destroy.success') }
      format.json { head :no_content }
    end
  end

  def current_navbar_item
    :vehicles
  end

  private

  def set_vehicle
    @vehicle = policy_scope(Vehicle).find_by(uuid: params[:vehicle_uuid])
  end

  def set_log_item_with_includes(includes)
    @log_item = policy_scope(LogItem).merge(@vehicle.log_items).includes(includes).find_by(uuid: params[:uuid])
    authorize @log_item
  end

  def set_log_item
    set_log_item_with_includes []
  end

  def set_shops
    @shops = policy_scope(Shop)
    @shop_options = (@shops.map { |shop| [shop.name || shop.uuid || 'Unknown shop', shop.uuid] }) + [['None', nil]]
  end

  # Only allow a list of trusted parameters through.
  def log_item_params
    extracted_params = params.require(:log_item).permit(:display_name, :include_time, :performed_at,
                                                        :odometer_reading_reading, :shop_uuid, :notes)
    transform_performed_at(extracted_params)
    extracted_params
  end
end

app/helpers/log_items_helper.rb
# frozen_string_literal: true

module LogItemsHelper
end

app/views/log_items/_form.html.erb
<%= bootstrap_form_with(model: [vehicle, log_item]) do |form| %>
  <p>
    <%= LogItem.human_attribute_name(:vehicle) %>:
    <%= link_to @vehicle.display_name, vehicle_path(@vehicle) %>
  </p>
  <%= form.text_field :display_name %>
  <%= form.text_area :notes %>
  <%= form.select :shop_uuid, @shop_options %>
  <%= form.text_field :odometer_reading_reading %>
  <%= form.datetime_field :performed_at,
                          value: convert_for_datetime_field(log_item.performed_at),
                          max: convert_for_datetime_field(Time.now) %>
  <p><%= t 'current_time_zone' %>: <%= current_user.tz.name %></p>
  <%= form.check_box :include_time %>
  <%= form.submit %>
<% end %>

app/views/log_items/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item"><%= link_to @vehicle.display_name, vehicle_path(@vehicle) %></li>
    <li class="breadcrumb-item"><%= link_to t('log_item.list.title'), vehicle_log_items_path(@vehicle) %></li>
    <li class="breadcrumb-item"><%= link_to @log_item.display_name, vehicle_log_item_path(@vehicle, @log_item) %></li>
    <li class="breadcrumb-item active"><%= t 'log_item.edit.title' %></li>
  </ol>
</nav>

<h1><%= t 'log_item.edit.title' %></h1>

<%= render "form", vehicle: @vehicle, log_item: @log_item %>

<br>

<div>
  <%= link_to "Show this log item", vehicle_log_item_path(@vehicle, @log_item) %> |
  <%= link_to "Back to log items", vehicle_log_items_path(@vehicle) %>
</div>

app/views/log_items/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item"><%= link_to @vehicle.display_name, vehicle_path(@vehicle) %></li>
    <li class="breadcrumb-item active"><%= t 'log_item.list.title' %></li>
  </ol>
</nav>

<h1>
  <%= t 'vehicle.log_items_title',
        vehicle: @vehicle.display_name %>
</h1>

<%= render(MaintenanceLogComponent.new(vehicle: @vehicle, log_items: @log_items)) %>

app/views/log_items/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item"><%= link_to @vehicle.display_name, vehicle_path(@vehicle) %></li>
    <li class="breadcrumb-item"><%= link_to t('log_item.list.title'), vehicle_log_items_path(@vehicle) %></li>
    <li class="breadcrumb-item active"><%= t 'log_item.create.title' %></li>
  </ol>
</nav>

<h1><%= t 'log_item.create.title' %></h1>

<%= render "form", vehicle: @vehicle, log_item: @log_item %>

<br>

<div>
  <%= link_to "Back to log items", vehicle_log_items_path(@vehicle) %>
</div>

app/views/log_items/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item"><%= link_to @vehicle.display_name, vehicle_path(@vehicle) %></li>
    <li class="breadcrumb-item"><%= link_to t('log_item.list.title'), vehicle_log_items_path(@vehicle) %></li>
    <li class="breadcrumb-item active"><%= @log_item.display_name %></li>
  </ol>
</nav>

<%= render(LogItemComponent.new(log_item: @log_item)) %>

<div>
  <%= link_to "Edit this log item", edit_vehicle_log_item_path(@vehicle, @log_item) %> |
  <%= link_to "Back to log items", vehicle_log_items_path(@vehicle) %>

  <%= button_to "Destroy this log item", vehicle_log_item_path(@vehicle, @log_item), method: :delete, class: 'btn btn-danger' %>
</div>