config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/graphql', to: 'graphql#execute'
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  ActiveAdmin.routes(self)
  mount Lookbook::Engine, at: '/lookbook'

  resources :tire_sets, param: :uuid
  resources :vehicles, param: :uuid do
    resources :odometer_readings, param: :uuid
    resources :log_items, param: :uuid
  end

  root 'vehicles#index'

  get '/login' => 'auth0#login'
  get '/auth/auth0/callback' => 'auth0#callback'
  post '/auth/developer/callback' => 'auth0#developer_callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'auth0#logout'

  get '/user' => 'user#me'
  put '/user' => 'user#update_me'
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  has_one_attached :photo
  has_many :log_items, dependent: :destroy
  has_many :odometer_readings, dependent: :destroy
  belongs_to :owner, class_name: 'User', optional: false
  before_save :convert_blank_to_nil
  validates :model_year, numericality: true, allow_nil: true

  owner_from_record

  def convert_blank_to_nil
    self.user_display_name = nil if user_display_name.blank?
    self.make = nil if make.blank?
    self.model = nil if model.blank?
    self.model_year = nil if model_year.blank?
    self.vin = nil if vin.blank?
  end

  def line_items
    LineItem.joins(:log_item).merge(log_items).distinct(:id)
  end

  def odometer
    odometer_readings.inverse_chrono.first&.reading || 0
  end

  def record_odometer_reading!(reading)
    OdometerReading.create(vehicle: self, performed_at: Time.zone.now, reading:)
  end

  def current_tires
    line_items
      .where_type('mountedTires')
      .with_field_value('tireSet')
      .inverse_chrono
      .first
      &.get_field_value('tireSet')
  end

  def display_model_year
    model_year || I18n.t('vehicle.unknown_year')
  end

  def display_make
    make || I18n.t('vehicle.unknown_make')
  end

  def display_model
    model || I18n.t('vehicle.unknown_model')
  end

  def generate_display_name
    "#{display_model_year} #{display_make} #{display_model}"
  end

  def display_name
    user_display_name || generate_display_name
  end

  def remove_photo=(should_remove)
    photo.purge_later if should_remove && should_remove != 0 && should_remove != '0'
  end

  def gid_class_name
    'vehicle'
  end
end

app/controllers/vehicles_controller.rb
# frozen_string_literal: true

class VehiclesController < ApplicationController
  SET_ACTIONS = %i[show edit update destroy].freeze

  include Secured
  include Pundit::Authorization
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: SET_ACTIONS + %i[index]

  before_action :set_vehicle, only: SET_ACTIONS

  # GET /vehicles or /vehicles.json
  def index
    @vehicles = policy_scope(Vehicle).includes(:photo_attachment, :owner)
  end

  # GET /vehicles/1 or /vehicles/1.json
  def show; end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
    authorize @vehicle
  end

  # GET /vehicles/1/edit
  def edit; end

  # POST /vehicles or /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.owner = current_user
    authorize @vehicle

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to vehicle_url(@vehicle), notice: I18n.t('vehicle.create.success') }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1 or /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to vehicle_url(@vehicle), notice: I18n.t('vehicle.update.success') }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1 or /vehicles/1.json
  def destroy
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: I18n.t('vehicle.destroy.success') }
      format.json { head :no_content }
    end
  end

  def current_navbar_item
    :vehicles
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = policy_scope(Vehicle).find_by(uuid: params[:uuid])
    authorize @vehicle
  end

  # Only allow a list of trusted parameters through.
  def vehicle_params
    params.require(:vehicle).permit(:breakin, :user_display_name, :make, :miles_per_year,
                                    :model, :vin, :model_year, :photo, :remove_photo)
  end
end

app/helpers/vehicles_helper.rb
# frozen_string_literal: true

module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= bootstrap_form_with(model: vehicle, data: { controller: 'vehicle--display-name' }) do |form| %>
  <% if @vehicle.photo.attached? %>
    <%= form.check_box :remove_photo %>
  <% else %>
    <%= form.file_field :photo %>
  <% end %>
  <%= form.text_field :vin %>
  <%= form.text_field :model_year, data: {
    action: 'vehicle--display-name#update',
    'vehicle--display-name-target' => 'modelYear'
  } %>
  <%= form.text_field :make, data: {
    action: 'vehicle--display-name#update',
    'vehicle--display-name-target' => 'make'
  } %>
  <%= form.text_field :model, data: {
    action: 'vehicle--display-name#update',
    'vehicle--display-name-target' => 'model'
  } %>
  <%= form.text_field :user_display_name, placeholder: vehicle.generate_display_name, data: { 'vehicle--display-name-target' => 'displayName' } %>
  <%= form.text_field :breakin %>
  <%= form.text_field :miles_per_year %>
  <%= form.submit %>
<% end %>

app/views/vehicles/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item"><%= link_to @vehicle.display_name, vehicle_path(@vehicle) %></li>
    <li class="breadcrumb-item active"><%= t 'vehicle.editing' %></li>
  </ol>
</nav>

<h1><%= t 'vehicle.editing' %></h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
  <%= link_to t('vehicle.link.show'), @vehicle %> |
  <%= link_to t('vehicle.link.back'), vehicles_path %>
</div>

app/views/vehicles/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item active"><%= t 'vehicle.list.title' %></li>
  </ol>
</nav>

<h1><%= t 'vehicle.list.title' %></h1>
<% if current_user.can_create_vehicle? %>
  <%= button_to t('vehicle.link.new'), new_vehicle_path, method: :get, class: 'btn btn-primary my-4' %>
<% elsif current_user.paid? %>
  <%= render(AlertComponent.new(color: :info)) do %>
    <%= t 'vehicle.list.cant_create.paid' %>
    <%= link_to t('user.go_to_subscriptions'), user_path, class: 'card-link' %>
  <% end %>
<% else %>
  <%= render(AlertComponent.new(color: :warning)) do %>
    <%= t 'vehicle.list.cant_create.free' %>
    <%= link_to t('user.create_subscription'), user_path, class: 'card-link' %>
  <% end %>
<% end %>

<%= render(CardsComponent.new) do |cards| %>
  <% @vehicles.each do |vehicle| %>
    <% cards.with_card(image: vehicle.photo.attached? ? url_for(vehicle.photo) : nil) do |card| %>
      <% card.with_header do %>
        <%= render(VehicleDisplayNameComponent.new(vehicle:)) %>
      <% end %>
      <% card.with_body do %>
        <%= render(VehicleComponent.new(vehicle:, current_user:, with_title: false, with_log: false)) %>
      <% end %>
      <% card.with_footer do %>
        <div class="btn-group">
          <% if policy(vehicle).show? %>
            <%= link_to t('vehicle.link.show'), vehicle_path(vehicle), class: 'btn btn-secondary' %>
          <% end %>
          <% if policy(vehicle).edit? %>
            <%= link_to t('vehicle.link.edit'), edit_vehicle_path(vehicle), class: 'btn btn-outline-secondary' %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/vehicles/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item active"><%= t 'vehicle.creating' %></li>
  </ol>
</nav>

<h1><%= t 'vehicle.creating' %></h1>

<%= render "form", vehicle: @vehicle %>

<br>

<div>
</div>

app/views/vehicles/odometer.html.erb
<h1>
  <%= t 'vehicle.odometer_title',
        vehicle: @vehicle.display_name,
        miles: t('miles', miles: number_with_delimiter(@vehicle.odometer)) %>
</h1>

<p>
  <%= link_to t('vehicle.link.vehicle_back', vehicle: @vehicle.display_name), vehicle_path(@vehicle) %>
</p>

<% default_accordion_item = if @odometer_reading && @vehicle.odometer_readings.empty?
                              :record
                            else
                              :list
                            end %>

<div class="accordion" id="odometerReadings">
  <% if @odometer_reading %>
    <div class="accordion-item">
      <h2 class="accordion-header" id="recordNewReadingHeading">
        <button
          class="accordion-button<%= if default_accordion_item == :record then '' else ' collapsed' end %>"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#recordNewReadingCollapse"
          aria-expanded="<%= default_accordion_item == :record %>"
          aria-controls="recordNewReadingCollapse">
          <%= t 'odometer_reading.create.title' %>
        </button>
      </h2>
      <div id="recordNewReadingCollapse" class="accordion-collapse collapse<%= if default_accordion_item == :record then ' show' else '' end %>" aria-labelledby="recordNewReadingHeading" data-bs-parent="#odometerReadings">
        <div class="accordion-body">
          <%= render 'odometer_readings/form', odometer_reading: @odometer_reading %>
        </div>
      </div>
    </div>
  <% end %>
  <div class="accordion-item">
    <h2 class="accordion-header" id="readingsHeading">
      <button
        class="accordion-button<%= if default_accordion_item == :list then '' else ' collapsed' end %>"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#readingsCollapse"
        aria-expanded="<%= default_accordion_item == :record %>"
        aria-controls="readingsCollapse">
        <%= OdometerReading.model_name.human(count: @vehicle.odometer_readings.count) %>
      </button>
    </h2>
    <div id="readingsCollapse" class="accordion-collapse collapse<%= if default_accordion_item == :list then ' show' else '' end %>" aria-labelledby="readingsHeading" data-bs-parent="#odometerReadings">
      <div class="accordion-body">
        <ul>
          <% @vehicle.odometer_readings.inverse_chrono.each do |odometer_reading| %>
            <li>
              <div class="d-flex align-items-center">
                <%= t(
                      'odometer_reading.preview',
                      reading: number_with_delimiter(odometer_reading.reading),
                      performed_at: display_time(
                        odometer_reading.performed_at,
                        format: if odometer_reading.include_time
                                  :date_and_time
                                else
                                  :date_only
                                end
                      )
                    ) %>
                <%= link_to t('odometer_reading.link.edit'), edit_odometer_reading_path(odometer_reading), class: 'mx-1 btn btn-sm btn-secondary' %>
                <%= button_to t('odometer_reading.link.destroy'), odometer_reading_path(odometer_reading), method: :delete, class: 'mx-1 btn btn-sm btn-danger' %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('vehicle.list.title'), vehicles_path %></li>
    <li class="breadcrumb-item active"><%= @vehicle.display_name %></li>
  </ol>
</nav>

<%= render(VehicleComponent.new(vehicle: @vehicle, current_user:, with_photo: true)) %>

<div>
  <p class="my-1">
    <%= link_to t('vehicle.link.back'), vehicles_path %>
  </p>
  <p class="my-1">
    <%= link_to t('vehicle.link.odometer'), vehicle_odometer_readings_path(@vehicle) %>
  </p>
  <p class="my-1">
    <%= link_to t('vehicle.link.log'), vehicle_log_items_path(@vehicle) %>
  </p>
  <% if policy(@vehicle).edit? %>
    <%= button_to t('vehicle.link.edit'), edit_vehicle_path(@vehicle), method: :get, class: 'btn btn-primary my-1' %>
  <% end %>
  <% if policy(@vehicle).destroy? %>
    <%= button_to t('vehicle.link.destroy'), @vehicle, method: :delete, class: 'btn btn-danger my-1' %>
  <% end %>
</div>