config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  post '/graphql', to: 'graphql#execute'
  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql'
  ActiveAdmin.routes(self)
  mount Lookbook::Engine, at: '/lookbook'

  resources :tire_sets, param: :uuid
  resources :vehicles, param: :uuid do
    resources :odometer_readings, param: :uuid
    resources :log_items, param: :uuid
  end

  root 'vehicles#index'

  get '/login' => 'auth0#login'
  get '/auth/auth0/callback' => 'auth0#callback'
  post '/auth/developer/callback' => 'auth0#developer_callback'
  get '/auth/failure' => 'auth0#failure'
  get '/logout' => 'auth0#logout'

  get '/user' => 'user#me'
  put '/user' => 'user#update_me'
end

app/models/tire_set.rb
# frozen_string_literal: true

class TireSet < ApplicationRecord
  has_many :line_item_fields, foreign_key: :tire_set_value_id, dependent: :nullify, inverse_of: :tire_set_value
  belongs_to :owner, class_name: 'User', optional: false
  before_save :convert_blank_to_nil

  owner_from_record

  def convert_blank_to_nil
    self.user_display_name = nil if user_display_name.blank?
    self.make = nil if make.blank?
    self.model = nil if model.blank?
    self.tin = nil if tin.blank?
  end

  def line_items
    LineItem
      .joins(:line_item_fields)
      .merge(line_item_fields)
      .distinct(:id)
  end

  def log_items
    LogItem
      .joins(:line_items)
      .merge(line_items)
      .distinct(:id)
  end

  def current_vehicle
    mounted_line_item = line_items
                        .where_type('mountedTires')
                        .where_field_value('tireSet', self)
                        .inverse_chrono
                        .includes(log_item: :vehicle)
                        .first
    return nil if mounted_line_item.nil?

    dismounted_line_items = line_items
                            .where_type('dismountedTires')
                            .where_field_value('tireSet', self)
                            .where_vehicle(mounted_line_item.vehicle)
                            .where_after(mounted_line_item.performed_at)
    mounted_line_item.vehicle if dismounted_line_items.empty?
  end

  def odometer
    # Bullet chokes up on only conditionally using certain relations
    previous_bullet_value = Bullet.enable?
    Bullet.enable = false

    counter = 0
    mounted_on = nil
    mounted_at = nil
    log_items.includes(:odometer_reading, :vehicle).chrono.each do |log_item|
      if log_item.removed_tire_sets.exists?(id:)
        if log_item.odometer_reading
          counter += log_item.odometer_reading.reading - (mounted_at || 0)
        elsif log_item.vehicle
          counter += log_item.vehicle.odometer_readings.closest_to(log_item.performed_at).reading - (mounted_at || 0)
        end
        mounted_on = nil
        mounted_at = nil
      end
      next unless log_item.added_tire_sets.exists?(id:)

      if mounted_on && mounted_at
        last_before_this = mounted_on.odometer_readings.first_before(mounted_at)
        soonest_after_this = mounted_on.odometer_readings.soonest_after(mounted_at)
        counter += if last_before_this
                     last_before_this.reading - mounted_at
                   elsif soonest_after_this
                     soonest_after_this.reading - mounted_at
                   else
                     mounted_on.odometer - mounted_at
                   end
      elsif !mounted_on.nil?
        counter += mounted_on.odometer
      end

      mounted_at = log_item
                   .odometer_reading
                     &.reading ||
                   log_item
                   .vehicle
                   .odometer_readings
                   .closest_to(log_item.performed_at)
                     &.reading ||
                   0
      mounted_on = log_item.vehicle
    end
    counter += mounted_on.odometer - mounted_at if mounted_at && mounted_on
    counter + (base_miles || 0)
  ensure
    Bullet.enable = previous_bullet_value
  end

  def specs
    "#{spec_maybe(vehicle_type)}#{spec_maybe(width)}/#{spec_maybe(aspect_ratio)}#{spec_maybe(construction)}#{spec_maybe(diameter)} #{spec_maybe(load_index)}#{spec_maybe(speed_rating)}"
  end

  def origin
    log_items.chrono.first&.performed_at
  end

  def category
    if hidden
      :hidden
    elsif current_vehicle
      :mounted
    else
      :unmounted
    end
  end

  def display_make
    make || I18n.t('tire_set.unknown_make')
  end

  def display_model
    model || I18n.t('tire_set.unknown_model')
  end

  def generate_display_name
    "#{display_make} #{display_model} (#{specs})"
  end

  def display_name
    user_display_name || generate_display_name
  end

  def gid_class_name
    'tire_set'
  end

  private

  def spec_maybe(spec)
    if spec.blank? || (spec.is_a?(Numeric) && spec.zero?)
      '?'
    elsif spec.is_a? Numeric
      spec.round.to_s
    else
      spec.to_s
    end
  end
end

app/controllers/tire_sets_controller.rb
# frozen_string_literal: true

class TireSetsController < ApplicationController
  SET_ACTIONS = %i[show edit update destroy].freeze

  include Secured
  include Pundit::Authorization
  after_action :verify_authorized, except: :index
  after_action :verify_policy_scoped, only: SET_ACTIONS + %i[index]

  before_action :set_tire_set, only: SET_ACTIONS

  # GET /tire_sets or /tire_sets.json
  def index
    @tire_sets = policy_scope(TireSet).includes(:owner)
  end

  # GET /tire_sets/1 or /tire_sets/1.json
  def show; end

  # GET /tire_sets/new
  def new
    @tire_set = TireSet.new
    authorize @tire_set
  end

  # GET /tire_sets/1/edit
  def edit; end

  # POST /tire_sets or /tire_sets.json
  def create
    @tire_set = TireSet.new(tire_set_params)
    @tire_set.owner = current_user
    authorize @tire_set

    respond_to do |format|
      if @tire_set.save
        format.html { redirect_to tire_set_url(@tire_set), notice: I18n.t('tire_set.create.success') }
        format.json { render :show, status: :created, location: @tire_set }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tire_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tire_sets/1 or /tire_sets/1.json
  def update
    respond_to do |format|
      if @tire_set.update(tire_set_params)
        format.html { redirect_to tire_set_url(@tire_set), notice: I18n.t('tire_set.update.success') }
        format.json { render :show, status: :ok, location: @tire_set }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tire_set.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tire_sets/1 or /tire_sets/1.json
  def destroy
    @tire_set.destroy

    respond_to do |format|
      format.html { redirect_to tire_sets_url, notice: I18n.t('tire_set.destroy.success') }
      format.json { head :no_content }
    end
  end

  def current_navbar_item
    :tire_sets
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tire_set
    @tire_set = policy_scope(TireSet).find_by(uuid: params[:uuid])
    authorize @tire_set
  end

  # Only allow a list of trusted parameters through.
  def tire_set_params
    params.require(:tire_set).permit(:aspect_ratio, :base_miles, :breakin, :construction, :diameter, :hidden,
                                     :load_index, :make, :model, :speed_rating, :tin, :user_display_name, :vehicle_type, :width)
  end
end

app/helpers/tire_sets_helper.rb
# frozen_string_literal: true

module TireSetsHelper
end

app/views/tire_sets/_form.html.erb
<%= bootstrap_form_with(model: tire_set, data: { controller: 'tire-set--display-name-and-specs' }) do |form| %>
  <%= form.text_field :make, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'make'
  } %>
  <%= form.text_field :model, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'model'
  } %>
  <%= form.text_field :tin %>
  <%= form.text_field :user_display_name, placeholder: tire_set.generate_display_name, data: { 'tire-set--display-name-and-specs-target' => 'displayName' } %>
  <%= form.text_field :breakin %>
  <%= form.text_field :base_miles %>
  <%= form.check_box :hidden %>

  <h2><%= TireSet.human_attribute_name(:specs) %></h2>
  <p data-tire-set--display-name-and-specs-target="specs"><%= tire_set.specs %></p>
  <%= form.text_field :vehicle_type, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'vehicleType'
  } %>
  <%= form.text_field :width, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'width'
  } %>
  <%= form.text_field :aspect_ratio, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'aspectRatio'
  } %>
  <%= form.text_field :construction, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'construction'
  } %>
  <%= form.text_field :diameter, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'diameter'
  } %>
  <%= form.text_field :load_index, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'loadIndex'
  } %>
  <%= form.text_field :speed_rating, data: {
    action: 'tire-set--display-name-and-specs#update',
    'tire-set--display-name-and-specs-target' => 'speedRating'
  } %>

  <%= form.submit %>
<% end %>

app/views/tire_sets/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('tire_set.list.title'), tire_sets_path %></li>
    <li class="breadcrumb-item"><%= link_to @tire_set.display_name, tire_set_path(@tire_set) %></li>
    <li class="breadcrumb-item active"><%= t 'tire_set.editing' %></li>
  </ol>
</nav>

<h1><%= t 'tire_set.editing' %></h1>

<%= render "form", tire_set: @tire_set %>

<br>

<div>
  <%= link_to t('tire_set.link.show'), @tire_set %> |
  <%= link_to t('tire_set.link.back'), tire_sets_path %>
</div>

app/views/tire_sets/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item active"><%= t 'tire_set.list.title' %></li>
  </ol>
</nav>

<h1><%= t 'tire_set.list.title' %></h1>

<%= button_to t('tire_set.link.new'), new_tire_set_path, method: :get, class: 'btn btn-primary my-4' %>

<%= render(CardsComponent.new) do |cards| %>
  <% @tire_sets.each do |tire_set| %>
    <% cards.with_card do |card| %>
      <% card.with_header do %>
        <%= render(TireSetDisplayNameComponent.new(tire_set:)) %>
      <% end %>
      <% card.with_body do %>
        <%= render(TireSetComponent.new(tire_set:, current_user:, with_title: false)) %>
      <% end %>
      <% card.with_footer do %>
        <div class="btn-group">
          <% if policy(tire_set).show? %>
            <%= link_to t('tire_set.link.show'), tire_set_path(tire_set), class: 'btn btn-secondary' %>
          <% end %>
          <% if policy(tire_set).edit? %>
            <%= link_to t('tire_set.link.edit'), edit_tire_set_path(tire_set), class: 'btn btn-outline-secondary' %>
          <% end %>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/tire_sets/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('tire_set.list.title'), tire_sets_path %></li>
    <li class="breadcrumb-item active"><%= t 'tire_set.creating' %></li>
  </ol>
</nav>

<h1><%= t 'tire_set.creating' %></h1>

<%= render "form", tire_set: @tire_set %>

<br>

<div>
  <%= link_to t('tire_set.link.back'), tire_sets_path %>
</div>

app/views/tire_sets/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to t('home.title'), root_path %></li>
    <li class="breadcrumb-item"><%= link_to t('tire_set.list.title'), tire_sets_path %></li>
    <li class="breadcrumb-item active"><%= @tire_set.display_name %></li>
  </ol>
</nav>

<%= render(TireSetComponent.new(tire_set: @tire_set, current_user:)) %>

<div>
  <p class="my-1">
    <%= link_to t('tire_set.link.back'), tire_sets_path %>
  </p>
  <% if policy(@tire_set).edit? %>
    <%= button_to t('tire_set.link.edit'), edit_tire_set_path(@tire_set), method: :get, class: 'btn btn-primary my-1' %>
  <% end %>
  <% if policy(@tire_set).destroy? %>
    <%= button_to t('tire_set.link.destroy'), @tire_set, method: :delete, class: 'btn btn-danger my-1' %>
  <% end %>
</div>